service: auth-server

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  timeout: 30 # optional, in seconds, default is 6

functions:
  hello:
    handler: handler.hello
